from pathlib import Path

def schema_version() -> str: ...
def simulator_available() -> bool: ...
def source_fingerprint() -> str: ...
def simulate_json(input: str) -> str: ...
def simulate_file(
    input_path: str | Path,
    output_path: str | Path,
    events_path: str | Path | None = ...,
) -> None: ...
def simulate_vector_file(
    manifest_path: str | Path,
    output_path: str | Path,
    events_path: str | Path | None = ...,
) -> None: ...
def simulate_vector_file_profiled(
    manifest_path: str | Path,
    output_path: str | Path,
    profile_path: str | Path,
    events_path: str | Path | None = ...,
) -> None: ...
