"""Structural contract shared by independent indicator compiler concerns."""

from __future__ import annotations

import ast
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any, Never, Protocol

from .indicator_compiler_bindings import (
    Binding,
    _CallableRef,
    _ColumnBundleBinding,
    _DataProviderRef,
    _LambdaRef,
    _MappingBinding,
    _SequenceBinding,
    _StaticBinding,
)


class CompilerProtocol(Protocol):
    path: Path
    methods: Mapping[str, ast.FunctionDef | ast.AsyncFunctionDef]
    class_constants: Mapping[str, Any]
    instance_constants: dict[str, Any]
    module_functions: dict[str, ast.FunctionDef]
    method_ids: dict[str, str]
    specialized_method_ids: dict[tuple[str, str], str]
    compiling: set[str]
    compiled: set[str]
    compiled_specializations: set[tuple[str, str]]
    function_return_types: dict[str, str]
    function_static_returns: dict[str, Any]
    function_arities: dict[str, int]
    function_lookbacks: dict[str, dict[str, Any]]
    functions: list[dict[str, Any]]
    nodes: list[dict[str, Any]]
    node_types: dict[str, str]
    source_map: dict[str, dict[str, Any]]
    required_input_columns: set[str]
    produced_columns: set[str]
    informative_nodes: list[str]
    opcodes: set[str]
    current_function: str
    current_nodes: list[str]
    bindings: dict[str, Binding]
    return_node: str | None

    def compile_method(
        self,
        name: str,
        *,
        kind: str = "helper",
        static_arguments: Mapping[str, Any] | None = None,
        callable_arguments: Mapping[str, _CallableRef] | None = None,
    ) -> str: ...
    def _next_function_id(self) -> str: ...
    def statement(self, node: ast.stmt) -> None: ...
    def statements(self, statements: Sequence[ast.stmt]) -> None: ...
    def absolute_difference_block(self, statements: Sequence[ast.stmt], index: int) -> int: ...
    def lagged_array_pair_block(self, statements: Sequence[ast.stmt], index: int) -> int: ...
    def age_filter_block(self, statements: Sequence[ast.stmt], index: int) -> int: ...
    def opening_range_block(self, statements: Sequence[ast.stmt], index: int) -> int: ...
    def inside_bar_block(self, statements: Sequence[ast.stmt], index: int) -> int: ...
    def first_fire_block(self, statements: Sequence[ast.stmt], index: int) -> int: ...
    def column_write(self, target: ast.Subscript, value_node: ast.expr, node: ast.AST) -> None: ...
    def expression(self, node: ast.expr) -> str: ...
    def subscript(self, node: ast.Subscript) -> str: ...
    def indexed_string_call(
        self, call: ast.Call, *, index: int, source_node: ast.AST
    ) -> str | None: ...
    def binary(self, node: ast.BinOp) -> str: ...
    def compare(self, node: ast.Compare) -> str: ...
    def logical(
        self,
        node: ast.AST,
        operator_type: type[ast.operator] | type[ast.boolop],
        *,
        values: Sequence[ast.expr] | None = None,
    ) -> str: ...
    def select(
        self, node: ast.AST, condition_node: ast.expr, true_node: ast.expr, false_node: ast.expr
    ) -> str: ...
    def call(self, node: ast.Call) -> str: ...
    def multi_output_assignment(self, target: ast.Tuple | ast.List, node: ast.Call) -> None: ...
    def inline_tuple_helper_call(self, call: ast.Call, callable_name: str) -> list[str] | None: ...
    def array_call(self, node: ast.Call, callable_name: str) -> str: ...
    def indicator_output(self, call: ast.Call, index: int, source_node: ast.AST) -> str: ...
    def indicator_call(self, node: ast.Call) -> str: ...
    def indicator_call_parts(
        self, node: ast.Call, callable_name: str
    ) -> tuple[list[str], dict[str, Any]]: ...
    def emit_indicator_call(
        self,
        source_node: ast.AST,
        callable_name: str,
        inputs: Sequence[str],
        arguments: Mapping[str, Any],
        *,
        output: str | None = None,
    ) -> str: ...
    def method_call(self, node: ast.Call, callable_name: str) -> str: ...
    def window_call(self, node: ast.Call) -> str | None: ...
    def informative_merge(self, node: ast.Call) -> str: ...
    def callable_reference(self, node: ast.expr) -> _CallableRef | None: ...
    @staticmethod
    def lambda_reference(node: ast.expr) -> _LambdaRef | None: ...
    def _inline_lambda_call(self, node: ast.Call) -> str | None: ...
    def static_reference(self, node: ast.expr) -> _StaticBinding | None: ...
    @staticmethod
    def sequence_reference(node: ast.expr) -> _SequenceBinding | None: ...
    @staticmethod
    def mapping_reference(node: ast.expr) -> _MappingBinding | None: ...
    def array_index_write(self, target: ast.Subscript, value_node: ast.expr) -> bool: ...
    def mapping_write(self, target: ast.Subscript, value_node: ast.expr) -> bool: ...
    def static_loop_iterations(self, node: ast.For) -> list[tuple[Binding, ...]] | None: ...
    @staticmethod
    def data_provider_reference(node: ast.expr) -> _DataProviderRef | None: ...
    def column_bundle_reference(self, node: ast.expr) -> _ColumnBundleBinding | None: ...
    def concat_column_bundle(self, node: ast.Call, callable_name: str) -> str | None: ...
    def frame_source_call(self, call: ast.Call) -> str | None: ...
    def frame_empty_guard(self, node: ast.If) -> bool: ...
    def frame_drop_guard(self, node: ast.If) -> bool: ...
    def inplace_forward_fill(self, node: ast.Call) -> bool: ...
    def append_sequence(self, call: ast.Call) -> bool: ...
    def reduce_sequence_call(self, call: ast.Call, callable_name: str) -> str | None: ...
    def append_tag_call(self, call: ast.Call, callable_name: str) -> str | None: ...
    def try_static_value(self, node: ast.expr) -> tuple[bool, Any]: ...
    def _try_static_call(self, node: ast.Call) -> tuple[bool, Any]: ...
    def static_value(self, node: ast.expr) -> Any: ...
    def resolved_callable(self, node: ast.expr) -> str: ...
    def literal(self, node: ast.AST, value: Any) -> str: ...
    def emit(
        self,
        source_node: ast.AST,
        opcode: str,
        value_type: str,
        *,
        inputs: Sequence[str] = (),
        parameters: Mapping[str, Any] | None = None,
        lookback: Mapping[str, Any] | None = None,
    ) -> str: ...
    def lookback(self, node_id: str) -> dict[str, Any]: ...
    def node_static_value(self, node_id: str) -> tuple[bool, Any]: ...
    def merged_lookback(self, node_ids: Sequence[str]) -> dict[str, Any]: ...
    def unsupported(self, node: ast.AST, description: str) -> Never: ...
